### ISSUE TITLE
MACOSX bug?

### ISSUE THREAD

**Issue by andreltr** [serkor1/cryptoQuotes#16]
Hello,

I'm unable to install the package under MACOSX.  However, it works fine under Windows.  See the error message below,

ERROR: lazy loading failed for package ‘cryptoQuotes’
* removing ‘/Users/andreltr/Library/R/x86_64/4.2/library/cryptoQuotes’

The downloaded source packages are in
	‘/private/var/folders/xg/n17vb1ts5bv8rpn3qypd61y40000gn/T/RtmplhlRV4/downloaded_packages’
Warning message:
In install.packages(pkgs = "cryptoQuotes", dependencies = TRUE) :
  installation of package ‘cryptoQuotes’ had non-zero exit status
R> library(cryptoQuotes)
Error in library(cryptoQuotes) : 
  there is no package called ‘cryptoQuotes’
R> 

What could be its cause, please?

TIA,

André Luiz

**Comment by andreltr** [comment]
Hello,

The output from R Desktop under Windows is below,


> sessionInfo()
R version 4.3.2 (2023-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22631)

Matrix products: default


locale:
[1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8    LC_MONETARY=Portuguese_Brazil.utf8
[4] LC_NUMERIC=C                       LC_TIME=Portuguese_Brazil.utf8    

time zone: America/Sao_Paulo
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] cryptoQuotes_1.3.1 rvest_1.0.4        lubridate_1.9.3    forcats_1.0.0      stringr_1.5.1      purrr_1.0.2       
 [7] readr_2.1.5        tidyr_1.3.1        tibble_3.2.1       ggplot2_3.5.1      tidyverse_2.0.0    dplyr_1.1.4       

loaded via a namespace (and not attached):
 [1] gtable_0.3.5      jsonlite_1.8.8    compiler_4.3.2    tidyselect_1.2.1  xml2_1.3.6        scales_1.3.0      fastmap_1.1.1    
 [8] lattice_0.22-5    R6_2.5.1          generics_0.1.3    curl_5.2.1        htmlwidgets_1.6.4 munsell_0.5.1     tzdb_0.4.0       
[15] pillar_1.9.0      rlang_1.1.3       utf8_1.2.4        stringi_1.8.3     lazyeval_0.2.2    timechange_0.3.0  viridisLite_0.4.2
[22] plotly_4.10.4     cli_3.6.2         withr_3.0.0       magrittr_2.0.3    xts_0.14.0        digest_0.6.35     grid_4.3.2       
[29] rstudioapi_0.15.0 hms_1.1.3         lifecycle_1.0.4   vctrs_0.6.5       glue_1.7.0        data.table_1.15.4 zoo_1.8-12       
[36] fansi_1.0.6       colorspace_2.1-0  TTR_0.24.4        httr_1.4.7        tools_4.3.2       pkgconfig_2.0.3   htmltools_0.5.7  
> 

I´ll send the R Desktop under MACOSX ASAP.

Best.

**Comment by andreltr** [comment]
Hello,

The output you requested from sessionInfo() under MacOSX is below.  Firstly, I loaded a few packages as described.

library(dplyr)
library(tidyverse)
library(rvest)
library(curl)

Error: package or namespace load failed for ‘curl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/andreltr/Library/R/x86_64/4.2/library/curl/libs/curl.so':
  dlopen(/Users/andreltr/Library/R/x86_64/4.2/library/curl/libs/curl.so, 6): no suitable image found.  Did find:
	/Users/andreltr/Library/R/x86_64/4.2/library/curl/libs/curl.so: mach-o, but wrong architecture
	/Users/andreltr/Library/R/x86_64/4.2/library/curl/libs/curl.so: mach-o, but wrong architecture
In addition: Warning message:
package ‘curl’ was built under R version 4.4.0 

library(cryptoQuotes)

R> devtools::install_github(
...     repo = 'https://github.com/serkor1/cryptoQuotes/',
...     ref  = 'development'
... )
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘htmltools’ 0.5.6.1 is already loaded, but >= 0.5.7 is required

R> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.7.10

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] quarto_1.3                 GetFREData_0.8.1           GetDFPData2_0.6.3          GetBCBData_0.7.0           BatchGetSymbols_2.6.4     
 [6] GetQuandlData_1.0.0        GetTDData_1.5.4            yfR_1.1.0                  shiny_1.7.5.1              tensorflow_2.14.0         
[11] keras_2.13.0               palmerpenguins_0.1.1       extrafont_0.19             RColorBrewer_1.1-3         ecoseries_0.1.5           
[16] powerjoin_0.1.0            reshape_0.8.9              ggthemr_1.1.0              ggpubr_0.6.0               ggrepel_0.9.4             
[21] ggthemes_4.2.4             egg_0.4.5                  gridExtra_2.3              forcats_1.0.0              stringr_1.5.1             
[26] dplyr_1.1.4                purrr_1.0.2                readr_2.1.4                tibble_3.2.1               ggplot2_3.4.4             
[31] tidyverse_2.0.0            here_1.0.1                 rvest_1.0.3                lubridate_1.9.3            tidyr_1.3.0               
[36] timetk_2.8.4               cowplot_1.1.1              reshape2_1.4.4             lattice_0.21-9             directlabels_2023.8.25    
[41] scales_1.3.0               bizdays_1.0.13             RSQLite_2.3.1              fst_0.9.8                  RcppSimdJson_0.1.10       
[46] simfinapi_0.2.4            ipeadatar_0.1.6            Quandl_2.11.0              Rcpp_1.0.11                PerformanceAnalytics_2.0.4
[51] xts_0.13.1                 zoo_1.8-12                 qlcal_0.0.8                magrittr_2.0.3             svDialogs_1.1.0           
[56] usethis_2.2.2             

loaded via a namespace (and not attached):
  [1] utf8_1.2.4          reticulate_1.34.0   tidyselect_1.2.0    munsell_0.5.0       codetools_0.2-19    dials_1.2.0        
  [7] future_1.33.0       miniUI_0.1.1.1      withr_2.5.2         audio_0.1-11        colorspace_2.1-0    progressr_0.14.0   
 [13] knitr_1.44          rstudioapi_0.15.0   ggsignif_0.6.4      Rttf2pt1_1.3.12     listenv_0.9.0       bit64_4.0.5        
 [19] DiceDesign_1.9      svGUI_1.0.1         rprojroot_2.0.4     parallelly_1.36.0   vctrs_0.6.5         generics_0.1.3     
 [25] xfun_0.40           ipred_0.9-14        timechange_0.2.0    R6_2.5.1            RJSONIO_1.3-1.8     bitops_1.0-7       
 [31] lhs_1.1.6           cachem_1.0.8        promises_1.2.1      nnet_7.3-19         gtable_0.3.4        globals_0.16.2     
 [37] beepr_1.3           processx_3.8.3      timeDate_4022.108   rlang_1.1.1         workflows_1.1.3     zeallot_0.1.0      
 [43] splines_4.2.0       rstatix_0.7.2       extrafontdb_1.0     yardstick_1.2.0     broom_1.0.5         checkmate_2.2.0    
 [49] yaml_2.3.8          abind_1.4-5         backports_1.5.0     httpuv_1.6.11       tools_4.2.0         lava_1.7.2.1       
 [55] ellipsis_0.3.2      parsnip_1.1.1       plyr_1.8.9          base64enc_0.1-3     RCurl_1.98-1.12     ps_1.7.6           
 [61] prettyunits_1.2.0   rpart_4.1.21        fs_1.6.3            furrr_0.3.1         IKTrading_1.0       data.table_1.14.8  
 [67] GPfit_1.0-8         whisker_0.4.1       pkgload_1.3.3       evaluate_0.22       hms_1.1.3           mime_0.12          
 [73] xtable_1.8-4        tfruns_1.5.1        compiler_4.2.0      crayon_1.5.2        htmltools_0.5.6.1   later_1.3.2        
 [79] tzdb_0.4.0          DBI_1.1.3           MASS_7.3-60         Matrix_1.5-4.1      car_3.1-2           cli_3.6.2          
 [85] quadprog_1.5-8      parallel_4.2.0      gower_1.0.1         pkgconfig_2.0.3     recipes_1.0.8       xml2_1.3.6         
 [91] foreach_1.5.2       hardhat_1.3.0       prodlim_2023.08.28  snakecase_0.11.1    callr_3.7.3         digest_0.6.33      
 [97] janitor_2.2.0       rmarkdown_2.25      rjson_0.2.21        lifecycle_1.0.4     jsonlite_1.8.8      carData_3.0-5      
[103] tune_1.1.2          fansi_1.0.6         pillar_1.9.0        fstcore_0.9.14      fastmap_1.1.1       httr_1.4.7         
[109] pkgbuild_1.4.2      survival_3.5-7      remotes_2.4.2.1     glue_1.6.2          fortunes_1.5-4      png_0.1-8          
[115] iterators_1.0.14    bit_4.0.5           class_7.3-22        stringi_1.8.3       blob_1.2.4          rsample_1.2.0      
[121] memoise_2.0.1       future.apply_1.11.0
R>

Best.

**Comment by andreltr** [comment]
Hello,

Eventually, I did try to install it in a different way with the following results,


R> install.packages("cryptoQuotes")
Installing package into ‘/Users/andreltr/Library/R/x86_64/4.2/library’
(as ‘lib’ is unspecified)
also installing the dependency ‘xts’


  There is a binary version available but the source version is later:
    binary source needs_compilation
xts 0.13.1 0.14.0              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Yes
installing the source packages ‘xts’, ‘cryptoQuotes’

trying URL 'http://cran.r-project.org/src/contrib/xts_0.14.0.tar.gz'
Content type 'application/x-gzip' length 485151 bytes (473 KB)
==================================================
downloaded 473 KB

trying URL 'http://cran.r-project.org/src/contrib/cryptoQuotes_1.3.1.tar.gz'
Content type 'application/x-gzip' length 4486489 bytes (4.3 MB)
==================================================
downloaded 4.3 MB


Bem vindo ao R em  Wed Jun 19 23:58:26 2024 


Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Attaching package: ‘lubridate’

The following object is masked from ‘package:cowplot’:

    stamp

The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

here() starts at /Users/andreltr
── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr   1.1.4     ✔ readr   2.1.4
✔ forcats 1.0.0     ✔ stringr 1.5.1
✔ ggplot2 3.4.4     ✔ tibble  3.2.1
✔ purrr   1.0.2     
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ readr::col_factor()     masks scales::col_factor()
✖ purrr::discard()        masks scales::discard()
✖ tidyr::extract()        masks magrittr::extract()
✖ dplyr::filter()         masks stats::filter()
✖ dplyr::first()          masks xts::first()
✖ readr::guess_encoding() masks rvest::guess_encoding()
✖ dplyr::last()           masks xts::last()
✖ purrr::set_names()      masks magrittr::set_names()
✖ lubridate::stamp()      masks cowplot::stamp()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘gridExtra’

The following object is masked from ‘package:dplyr’:

    combine

Registering fonts with R
2024-06-19 23:58:40.235991: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

During startup - There were 13 warnings (use warnings() to see them)
* installing *source* package ‘xts’ ...
** package ‘xts’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c add_class.c -o add_class.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c any.c -o any.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c attr.c -o attr.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c binsearch.c -o binsearch.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c coredata.c -o coredata.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c dimnames.c -o dimnames.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c endpoints.c -o endpoints.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c extract_col.c -o extract_col.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c isOrdered.c -o isOrdered.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c isXts.c -o isXts.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c lag.c -o lag.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c merge.c -o merge.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c na.c -o na.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c period_apply.c -o period_apply.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c period_arithmetic.c -o period_arithmetic.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c period_quantile.c -o period_quantile.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c rbind.c -o rbind.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c rollfun.c -o rollfun.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c runSum.c -o runSum.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c startofyear.c -o startofyear.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c subset.c -o subset.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c subset.old.c -o subset.old.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c toperiod.c -o toperiod.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c totalcols.c -o totalcols.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c tryXts.c -o tryXts.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include -I'/Library/Frameworks/R.framework/Versions/4.2/Resources/library/zoo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c unique.time.c -o unique.time.o
clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o xts.so add_class.o any.o attr.o binsearch.o coredata.o dimnames.o endpoints.o extract_col.o init.o isOrdered.o isXts.o lag.o merge.o na.o period_apply.o period_arithmetic.o period_quantile.o rbind.o rollfun.o runSum.o startofyear.o subset.o subset.old.o toperiod.o totalcols.o tryXts.o unique.time.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Users/andreltr/Library/R/x86_64/4.2/library/00LOCK-xts/00new/xts/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading

Bem vindo ao R em  Wed Jun 19 23:58:59 2024 


Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Attaching package: ‘lubridate’

The following object is masked from ‘package:cowplot’:

    stamp

The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

here() starts at /private/var/folders/xg/n17vb1ts5bv8rpn3qypd61y40000gn/T/Rtmp8FgYhn/R.INSTALL1981427b6342/xts
── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr   1.1.4     ✔ readr   2.1.4
✔ forcats 1.0.0     ✔ stringr 1.5.1
✔ ggplot2 3.4.4     ✔ tibble  3.2.1
✔ purrr   1.0.2     
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ readr::col_factor()     masks scales::col_factor()
✖ purrr::discard()        masks scales::discard()
✖ tidyr::extract()        masks magrittr::extract()
✖ dplyr::filter()         masks stats::filter()
✖ dplyr::first()          masks xts::first()
✖ readr::guess_encoding() masks rvest::guess_encoding()
✖ dplyr::last()           masks xts::last()
✖ purrr::set_names()      masks magrittr::set_names()
✖ lubridate::stamp()      masks cowplot::stamp()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘gridExtra’

The following object is masked from ‘package:dplyr’:

    combine

Registering fonts with R
2024-06-19 23:59:10.177004: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

During startup - There were 13 warnings (use warnings() to see them)
Error: package ‘xts’ is required by ‘Quandl’ so will not be detached
Execution halted
ERROR: lazy loading failed for package ‘xts’
* removing ‘/Users/andreltr/Library/R/x86_64/4.2/library/xts’
* restoring previous ‘/Users/andreltr/Library/R/x86_64/4.2/library/xts’
Warning in install.packages :
  installation of package ‘xts’ had non-zero exit status

Bem vindo ao R em  Wed Jun 19 23:59:14 2024 


Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Attaching package: ‘lubridate’

The following object is masked from ‘package:cowplot’:

    stamp

The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

here() starts at /Users/andreltr
── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr   1.1.4     ✔ readr   2.1.4
✔ forcats 1.0.0     ✔ stringr 1.5.1
✔ ggplot2 3.4.4     ✔ tibble  3.2.1
✔ purrr   1.0.2     
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ readr::col_factor()     masks scales::col_factor()
✖ purrr::discard()        masks scales::discard()
✖ tidyr::extract()        masks magrittr::extract()
✖ dplyr::filter()         masks stats::filter()
✖ dplyr::first()          masks xts::first()
✖ readr::guess_encoding() masks rvest::guess_encoding()
✖ dplyr::last()           masks xts::last()
✖ purrr::set_names()      masks magrittr::set_names()
✖ lubridate::stamp()      masks cowplot::stamp()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘gridExtra’

The following object is masked from ‘package:dplyr’:

    combine

Registering fonts with R
2024-06-19 23:59:24.774828: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

During startup - There were 13 warnings (use warnings() to see them)
* installing *source* package ‘cryptoQuotes’ ...
** package ‘cryptoQuotes’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading

Bem vindo ao R em  Wed Jun 19 23:59:30 2024 


Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Attaching package: ‘lubridate’

The following object is masked from ‘package:cowplot’:

    stamp

The following objects are masked from ‘package:base’:

    date, intersect, setdiff, union

here() starts at /private/var/folders/xg/n17vb1ts5bv8rpn3qypd61y40000gn/T/Rtmp1scQmt/R.INSTALL19f73a393a09/cryptoQuotes
── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr   1.1.4     ✔ readr   2.1.4
✔ forcats 1.0.0     ✔ stringr 1.5.1
✔ ggplot2 3.4.4     ✔ tibble  3.2.1
✔ purrr   1.0.2     
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ readr::col_factor()     masks scales::col_factor()
✖ purrr::discard()        masks scales::discard()
✖ tidyr::extract()        masks magrittr::extract()
✖ dplyr::filter()         masks stats::filter()
✖ dplyr::first()          masks xts::first()
✖ readr::guess_encoding() masks rvest::guess_encoding()
✖ dplyr::last()           masks xts::last()
✖ purrr::set_names()      masks magrittr::set_names()
✖ lubridate::stamp()      masks cowplot::stamp()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘gridExtra’

The following object is masked from ‘package:dplyr’:

    combine

Registering fonts with R
2024-06-19 23:59:40.594827: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

During startup - There were 13 warnings (use warnings() to see them)
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/andreltr/Library/R/x86_64/4.2/library/curl/libs/curl.so':
  dlopen(/Users/andreltr/Library/R/x86_64/4.2/library/curl/libs/curl.so, 6): no suitable image found.  Did find:
	/Users/andreltr/Library/R/x86_64/4.2/library/curl/libs/curl.so: mach-o, but wrong architecture
	/Users/andreltr/Library/R/x86_64/4.2/library/curl/libs/curl.so: mach-o, but wrong architecture
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘cryptoQuotes’
* removing ‘/Users/andreltr/Library/R/x86_64/4.2/library/cryptoQuotes’
Warning in install.packages :
  installation of package ‘cryptoQuotes’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/xg/n17vb1ts5bv8rpn3qypd61y40000gn/T/Rtmpx0tccL/downloaded_packages’

R>

**Comment by serkor1** [comment]
Hi @andreltr,

Thank you for the output. Firstly, I wasn't able to reproduce the installation error on my own OSX. Secondly, there is no failed `CRAN`-checks. Based on this, and your output I see a few possible sources for installation error:

- You are using `R` version `4.2`, try updating to the latest stable version. This should solve most problems. I see that `{curl}` and `{htmltools}` is causing some issues here, so reinstall it after you update `R`.
- (This is a wild guess) If you don't have [`xcode`](https://developer.apple.com/xcode/) installed, please do. This should solve compiling issues.

I hope this helps. :smile: 

Best,

**Comment by serkor1** [comment]
Hi @andreltr,

I am closing this issue as I haven't heard from you. If the issue still persists, feel free to reopen this issue.

Best,

**Comment by andreltr** [comment]
Hello @serkor1,

Issue solved, thanks! 
If I may, I'd like to suggest the index could be just a plain numbered sequential order instead of the actual timestamp. 
Maybe the timestamp could be split in two columns: one for the its date and the other for the time of its occurrence.  Both could be of type Date.
I don't know if R allows several indexes.
Best.
