### ISSUE TITLE
[BUG] Browser does not open when generating a graph from a script

### ISSUE THREAD

**Issue by shapeshed** [serkor1/cryptoQuotes#34]
Firstly thank you for this excellent library! I am quite new to R so it is possible that there could be a misconfiguration in my R environment. 

I would like to run an R script rather than generate graphs from the R console. When I do this the browser does not open. However if I run the same code in the console it works fine. 

```sh
cat ~/.Rprofile
options(browser = "/usr/bin/firefox")
```

**Session Information**
```r
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.12.0
LAPACK: /usr/lib/liblapack.so.3.12.0

locale:
 [1] LC_CTYPE=en_GB.utf8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.utf8        LC_COLLATE=en_GB.utf8
 [5] LC_MONETARY=en_GB.utf8    LC_MESSAGES=en_GB.utf8
 [7] LC_PAPER=en_GB.utf8       LC_NAME=C
 [9] LC_ADDRESS=C              LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.utf8 LC_IDENTIFICATION=C

time zone: Europe/London
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.4.1

```

**To Reproduce**

Save the following R code as `ethereum.R`. Run with `Rscript ethereum.R`. Observe that the browser does not open. 

Paste the same code into a R Console. The browser does open. 

```r
# Load necessary libraries (if not loaded, you may need to install them first)
# install.packages("cryptoQuotes")
# library(cryptoQuotes)
options(browser = "/usr/bin/firefox")


# Fetch historical data for Ethereum (ETH)
ETH <- cryptoQuotes::get_quote(
  ticker   = 'ETHUSDT',
  source   = 'binance',
  futures  = FALSE,
  interval = '4h',
  from     = Sys.Date() - 30
)

# Fetch long/short ratio data for Ethereum
ETH_LS <- cryptoQuotes::get_lsratio(
  ticker   = 'ETHUSDT',
  source   = 'binance',
  interval = '4h',
  from     = Sys.Date() - 30
)

# Generate a chart with price, volume, long/short ratio, and indicators
cryptoQuotes::chart(
  ticker = ETH,
  main   = cryptoQuotes::kline(),
  sub    = list(
    cryptoQuotes::lsr(ratio = ETH_LS),
    cryptoQuotes::volume()
  ),
  indicator = list(
    cryptoQuotes::sma(n = 7),
    cryptoQuotes::sma(n = 14),
    cryptoQuotes::sma(n = 21),
    cryptoQuotes::bollinger_bands()
  )
)

```

**Expected behavior**
The browser opens and displays the graph, allowing scripts to be used.

**Comment by serkor1** [comment]
Hi @shapeshed,

Welcome to the `R` community, and thank you for a good issue. This issue is more related to how {plotly} and R Studio works - and not something that I can fix. However, we could work on a small hack;

Consider this simple `atom_chart.R`-script:

```R
# 1) generate chart
rocket_chart <- cryptoQuotes::chart(
    ticker = cryptoQuotes::ATOM,
    main   = cryptoQuotes::kline(),
    sub    = cryptoQuotes::volume()
)
    
# 2) store the chart
# as html
htmlwidgets::saveWidget(
    rocket_chart,
    file = "rocket_chart.html"
)

# 3) open the file
# using browseURL
browseURL("rocket_chart.html")
```

As the `chart()`-function is a wrapper of {plotly} and produces a bunch of Java and HTML code, we can just save it as a HTML widget using the {htmlwidgets}-package.

```sh
$ Rscript atom_chart.R
```

Which should produce the chart, store it locally and then open your default browser!

Let me know how it works out!

**Comment by shapeshed** [comment]
Thank you for taking the time to look at this and for the comprehensive answer!

This resolves my issue!

If I get more fluent in R I would be interested in contributing the project if you need help and there are good first issues.

**Comment by serkor1** [comment]
You are more than welcome to contribute - I have bunch of updates on the `chart`-family of functions that needs a minor revamp in the back-end side of the package when the time is.

In the meantime - if you haven't seen the book yet - I can recommend [Deep R Programming](https://deepr.gagolewski.com/) by Marek Gagolewski which is a highly valuable book if you plan to develop and contribute to software in R generally.
