### ISSUE TITLE
Feature request: Perpetual features

### ISSUE THREAD

**Issue by MislavSag** [serkor1/cryptoQuotes#6]
Thank you for great package.

I would like to add feature request. I am not sure if this is on your roadmap, but I would like to be able to retrieve 2 kinds of data for futures:
- funding rates (example dat from binance https://data.binance.vision/?prefix=data/futures/um/monthly/fundingRate/)
-  perpetual futures data. I am not sure if they are available through your package.

**Comment by serkor1** [comment]
Thank you for your feedback, and request. Much appreciated.

Funding rates are currently in the roadmap, which will be featured in the next major update due March. Along with updated visualization, and global market capitalization.

In the `getQuote()`-function, there is a  `futures`-argument which extracts perpetual futures market data - is this what you are referring to regarding your second bullet?

**Comment by serkor1** [comment]
@MislavSag can I close the issue regarding your second question, or do I need to do a review of my code?

At the moment all Futures endpoints supports Mark, Index and Last price.

In the current setup it fetches the Last price. I did consider adding an options so user can choose which price to fetch, but this made the main function too low-level for my liking.

So at the moment I am considering splitting the function in two: one for spot, on for futures.

Let me hear your thoughts!
